# Generated by Django 4.0.4 on 2022-04-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Material', models.CharField(max_length=30)),
                ('EMail', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Value', models.IntegerField()),
                ('Type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('EMail', models.EmailField(max_length=30)),
                ('Address', models.TextField()),
                ('PassWord', models.TextField()),
            ],
        ),
    ]
