# Generated by Django 4.0.4 on 2022-04-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='PhNo',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
